<div class="table-header">Results <span class="pull-right">{{ number_format($employees->total()) }} employees &middot; {{ \Carbon\Carbon::parse($month.'-01')->format('F Y') }}</span></div>
<div class="table-responsive"><table class="table table-striped table-bordered table-hover"><thead><tr><th style="width:34px"></th><th>Employee Name</th><th>Machine Code</th><th>Department</th><th>Shift</th><th>Working Days</th><th>Present</th><th>Absent</th><th>Early Min</th><th>Late Min</th></tr></thead><tbody>
@forelse($employees as $employee)
@php($selected=isset($selectedEmployee)&&$selectedEmployee?->id===$employee->id)
<tr class="{{ $selected ? 'info' : '' }}" style="cursor:pointer" onclick="window.location='{{ route('employees.index',array_merge(request()->except('page'),['employee'=>$employee->id,'month'=>$month])) }}#employee-details'">
<td><input type="radio" tabindex="-1" {{ $selected?'checked':'' }}></td><td><strong>{{ $employee->name }}</strong>@unless($employee->is_active) <span class="label label-default">Inactive</span>@endunless</td><td>{{ $employee->empid }}</td><td>{{ $employee->department }}</td><td>{{ $employee->shift?->name ?? '—' }}</td><td>{{ $employee->working_days }}</td><td class="green">{{ $employee->present_days }}</td><td class="red">{{ $employee->absent_days }}</td><td>{{ $employee->shift ? $employee->attendance->sum('early_minutes') : '—' }}</td><td>{{ $employee->shift ? $employee->attendance->sum('late_minutes') : '—' }}</td></tr>
@empty<tr><td colspan="10" class="empty-state"><i class="fa fa-users"></i><p>No employees match these filters.</p><a href="{{ route('employees.create') }}">Add an employee</a></td></tr>@endforelse
</tbody></table></div>@include('partials.pagination',['records'=>$employees])
<p class="help-block">Click an employee row to show their details and daily attendance below.</p>
