@extends('layouts.app')
@section('title','Attendance Reports')
@section('subtitle','Build focused employee attendance reports')
@section('content')
<style>
.report-builder{background:#fff;border:1px solid #e5e9ef;border-radius:8px;margin-bottom:18px}.report-builder__head{padding:18px 20px;border-bottom:1px solid #eef1f4}.report-builder__head h4{margin:0 0 4px;font-weight:600}.report-builder__head p{margin:0;color:#7b8794}.report-builder__body{padding:18px 20px}.report-grid{display:grid;grid-template-columns:1fr 1fr 1.6fr;gap:16px}.report-field label{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:#667085;margin-bottom:7px;font-weight:600}.employee-select option{padding:6px}.status-picker{display:flex;gap:8px;flex-wrap:wrap}.status-check{margin:0;cursor:pointer}.status-check input{display:none}.status-check span{display:block;padding:8px 13px;border:1px solid #dfe3e8;border-radius:5px;background:#fff;color:#505a66;font-weight:500}.status-check input:checked+span{border-color:#438eb9;background:#f2f8fc;color:#26719c}.report-actions{display:flex;justify-content:space-between;align-items:center;gap:10px;padding-top:16px;margin-top:16px;border-top:1px solid #eef1f4}.report-actions__right{display:flex;gap:7px;flex-wrap:wrap}.employee-context{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:#e8edf2;border:1px solid #e8edf2;border-radius:7px;overflow:hidden;margin-bottom:18px}.employee-context>div{background:#fff;padding:13px 15px}.employee-context small{display:block;color:#8a94a0;text-transform:uppercase;font-size:10px;letter-spacing:.05em;margin-bottom:4px}.employee-context strong{color:#36414d}.report-section{background:#fff;border:1px solid #e5e9ef;border-radius:7px;margin-top:18px;overflow:hidden}.report-section__head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid #e9edf2}.report-section__head h4{margin:0;font-size:15px;font-weight:600}.report-section__head span{font-size:12px;color:#7b8794}.report-section .table{margin-bottom:0}.report-overview{display:flex;justify-content:space-between;align-items:center;gap:20px;background:#fff;border:1px solid #e5e9ef;border-radius:7px;padding:14px 16px;margin-bottom:16px}.report-overview__title{font-size:17px;font-weight:600;color:#344054;line-height:1.25}.report-overview__range{font-size:12px;color:#7b8794;margin-top:4px}.report-overview__meta{display:flex;gap:24px;text-align:right}.report-overview__meta small{display:block;text-transform:uppercase;letter-spacing:.05em;font-size:9px;color:#98a2b3;margin-bottom:3px}.report-overview__meta strong{font-size:12px;color:#475467}.print-report-head{display:none}@media(max-width:900px){.report-grid{grid-template-columns:1fr}.employee-context{grid-template-columns:1fr 1fr}.report-actions{align-items:flex-start;flex-direction:column}.report-overview{align-items:flex-start;flex-direction:column}.report-overview__meta{text-align:left}}
@media print{
 @page{size:A4 landscape;margin:9mm}
 html,body{background:#fff!important;font-size:9px!important}.sidebar,.navbar,.breadcrumbs,.footer,.page-header,.report-builder,.report-overview,.report-summary,.infobox,.employee-context,.report-section.employee-summary{display:none!important}.main-content,.page-content{margin:0!important;padding:0!important}.print-report-head{display:grid!important;grid-template-columns:1fr auto;gap:20px;align-items:end;border-bottom:1.5px solid #222;padding:0 0 7px;margin:0 0 8px}.print-report-head__eyebrow{font-size:8px;text-transform:uppercase;letter-spacing:.12em;color:#666;margin-bottom:2px}.print-report-head h3{margin:0;font-size:16px;font-weight:700;line-height:1.15}.print-report-head__range{margin:3px 0 0;font-size:9px;color:#444}.print-report-head__meta{display:grid;grid-template-columns:auto auto;gap:5px 18px;text-align:right;font-size:9px}.print-report-head__meta small{display:block;font-size:7px;text-transform:uppercase;letter-spacing:.07em;color:#777}.print-report-head__meta strong{display:block;margin-top:1px;font-size:9px;color:#222}.report-section{border:0!important;margin:0!important;overflow:visible!important}.report-section__head{display:none!important}.table-responsive{overflow:visible!important}.table{width:100%!important;border-collapse:collapse!important;font-size:8.5px!important}.table th,.table td{padding:4px 5px!important;border:1px solid #bbb!important;vertical-align:middle!important}.table th{background:#f3f3f3!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.table tr{page-break-inside:avoid}.table thead{display:table-header-group}
}
</style>

<div class="report-builder">
 <div class="report-builder__head"><h4><i class="fa fa-filter"></i> Report Builder</h4><p>Choose a date range, an employee if required, and one or more attendance statuses.</p></div>
 <form method="get" class="report-builder__body">
  <div class="report-grid">
   <div class="report-field"><label>From date</label><input type="date" name="from" class="form-control" value="{{ $from->format('Y-m-d') }}" required></div>
   <div class="report-field"><label>To date</label><input type="date" name="to" class="form-control" value="{{ $to->format('Y-m-d') }}" required></div>
   <div class="report-field"><label>Employee</label><select name="employee" class="form-control employee-select"><option value="">All employees</option>@foreach($employees as $e)<option value="{{ $e->empid }}" @selected((string)request('employee')===(string)$e->empid)>{{ $e->name }} · ID {{ $e->empid }} · {{ $e->department ?: 'No department' }} · {{ $e->designation ?: 'No designation' }} · {{ $e->shift?->name ?: 'No shift' }}</option>@endforeach</select></div>
  </div>
  <div class="report-field" style="margin-top:16px"><label>Status <span style="text-transform:none;font-weight:400">— leave all unchecked for all statuses</span></label><div class="status-picker">@foreach($availableStatuses as $status)<label class="status-check"><input type="checkbox" name="statuses[]" value="{{ $status }}" @checked(in_array($status,$statuses,true))><span>{{ $status }}</span></label>@endforeach</div></div>
  <div class="report-actions"><div><button class="btn btn-info"><i class="fa fa-search"></i> Generate Report</button> <a href="{{ route('reports.index') }}" class="btn btn-default">Reset</a></div><div class="report-actions__right"><a href="{{ route('reports.excel',request()->query()) }}" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Excel</a><a href="{{ route('reports.csv',request()->query()) }}" class="btn btn-default"><i class="fa fa-file-text-o"></i> CSV</a><button type="button" onclick="window.print()" class="btn btn-primary"><i class="fa fa-print"></i> Print</button></div></div>
 </form>
</div>

<div class="report-overview"><div><div class="report-overview__title">Attendance Report — {{ $periodLabel }}</div><div class="report-overview__range"><i class="fa fa-calendar"></i> {{ $from->format('d M Y') }} – {{ $to->format('d M Y') }}</div></div><div class="report-overview__meta"><div><small>Employee</small><strong>{{ $selectedEmployee ? $selectedEmployee->name.' · '.$selectedEmployee->empid : 'All Employees' }}</strong></div><div><small>Status</small><strong>{{ $statuses ? implode(', ',$statuses) : 'All Statuses' }}</strong></div><div><small>Records</small><strong>{{ number_format($records->count()) }}</strong></div></div></div>
@if($selectedEmployee)
<div class="employee-context"><div><small>Employee</small><strong>{{ $selectedEmployee->name }}</strong></div><div><small>Employee ID</small><strong>{{ $selectedEmployee->empid }}</strong></div><div><small>Department</small><strong>{{ $selectedEmployee->department ?: '—' }}</strong></div><div><small>Designation</small><strong>{{ $selectedEmployee->designation ?: '—' }}</strong></div><div><small>Shift</small><strong>{{ $selectedEmployee->shift?->name ?: '—' }}</strong></div></div>
@endif

<x-summary :summary="$summary" />
<div class="row report-summary">@foreach(['Total Records'=>'list-alt','Employees'=>'users','Working Days'=>'briefcase','Late Min'=>'clock-o','Early Min'=>'sign-out','Attendance %'=>'line-chart'] as $label=>$icon)<div class="col-xs-6 col-md-3"><div class="infobox infobox-blue"><div class="infobox-icon"><i class="ace-icon fa fa-{{ $icon }}"></i></div><div class="infobox-data"><span class="infobox-data-number">{{ number_format($totals[$label]??0,$label==='Attendance %'?1:0) }}{{ $label==='Attendance %'?'%':'' }}</span><div class="infobox-content">{{ $label }}</div></div></div></div>@endforeach</div>

@if(!$selectedEmployee)
<div class="report-section employee-summary"><div class="report-section__head"><h4>Employee Summary</h4><span>{{ number_format($employeeRows->count()) }} employees</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>S.No</th><th>ID</th><th>Employee</th><th>Department</th><th>Designation</th><th>Shift</th><th>Present</th><th>Absent</th><th>Leave</th><th>Off</th><th>Late</th><th>Early</th><th>Attendance</th></tr></thead><tbody>@forelse($employeeRows as $i=>$r)<tr><td>{{ $i+1 }}</td><td>{{ $r->empid }}</td><td><strong>{{ $r->name }}</strong></td><td>{{ $r->department }}</td><td>{{ $r->designation }}</td><td>{{ $r->shift }}</td><td>{{ $r->present }}</td><td>{{ $r->absent }}</td><td>{{ $r->leave }}</td><td>{{ $r->off }}</td><td>{{ $r->late }}m</td><td>{{ $r->early }}m</td><td><strong>{{ number_format($r->percentage,1) }}%</strong></td></tr>@empty<tr><td colspan="13" class="text-center text-muted">No records match this report.</td></tr>@endforelse</tbody></table></div></div>
@endif

<div class="print-report-head"><div><div class="print-report-head__eyebrow">Attendance Report</div><h3>{{ $periodLabel }}</h3><p class="print-report-head__range">{{ $from->format('d M Y') }} – {{ $to->format('d M Y') }}</p></div><div class="print-report-head__meta"><div><small>Employee</small><strong>{{ $selectedEmployee ? $selectedEmployee->name.' · '.$selectedEmployee->empid : 'All Employees' }}</strong></div><div><small>Status</small><strong>{{ $statuses ? implode(', ',$statuses) : 'All Statuses' }}</strong></div><div><small>Records</small><strong>{{ number_format($records->count()) }}</strong></div><div><small>Generated</small><strong>{{ now()->format('d M Y, h:i A') }}</strong></div></div></div>
<div class="report-section"><div class="report-section__head"><h4>Attendance Details</h4><span>{{ number_format($records->count()) }} records</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>S.No</th><th>Date</th>@if(!$selectedEmployee)<th>Employee</th><th>Department</th>@endif<th>Status</th><th>Check In</th><th>Check Out</th><th>Working Hours</th><th>Late Min</th><th>Early Min</th></tr></thead><tbody>@forelse($records as $i=>$r)<tr><td>{{ $i+1 }}</td><td>{{ $r->date?->format('d M Y') }}</td>@if(!$selectedEmployee)<td><strong>{{ $r->employee?->name }}</strong><br><small class="text-muted">ID {{ $r->empid }}</small></td><td>{{ $r->employee?->department }}</td>@endif<td>{{ $r->status }}</td><td>{{ $r->check_in?->format('h:i A') ?? '—' }}</td><td>{{ $r->check_out?->format('h:i A') ?? '—' }}</td><td>{{ $r->working_hours }}</td><td>{{ $r->late_minutes ?? 0 }}</td><td>{{ $r->early_minutes ?? 0 }}</td></tr>@empty<tr><td colspan="{{ $selectedEmployee?8:10 }}" class="text-center text-muted">No attendance records found for the selected filters.</td></tr>@endforelse</tbody></table></div></div>
@endsection
