<?php
namespace LocalAttendanceAgent;
use PDO;
class AgentState {
 private PDO $db;
 public function __construct(string $path) { $this->db=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $this->db->exec('CREATE TABLE IF NOT EXISTS pending_batches (batch_id TEXT PRIMARY KEY,payload TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)'); $this->db->exec('CREATE TABLE IF NOT EXISTS failed_batches (batch_id TEXT PRIMARY KEY,payload TEXT NOT NULL,reason TEXT NOT NULL,http_status INTEGER NULL,failed_at INTEGER NOT NULL)'); $this->db->exec('CREATE TABLE IF NOT EXISTS attendance_records (fingerprint TEXT PRIMARY KEY,batch_id TEXT NULL,status TEXT NOT NULL,first_seen_at INTEGER NOT NULL,acked_at INTEGER NULL,last_error TEXT NULL)'); $this->db->exec('CREATE INDEX IF NOT EXISTS attendance_records_status_idx ON attendance_records(status)'); $this->db->exec('CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY,value TEXT NULL)'); }
 public function queue(string $id,array $payload):void { $s=$this->db->prepare('INSERT OR IGNORE INTO pending_batches (batch_id,payload,created_at) VALUES (?,?,?)'); $s->execute([$id,json_encode($payload,JSON_THROW_ON_ERROR),time()]); }
 public function dueBatches():array { $s=$this->db->prepare('SELECT * FROM pending_batches WHERE next_attempt_at <= ? ORDER BY created_at ASC'); $s->execute([time()]); return $s->fetchAll(PDO::FETCH_ASSOC); }
 public function acknowledge(string $id):void { $s=$this->db->prepare('DELETE FROM pending_batches WHERE batch_id=?'); $s->execute([$id]); }
 public function retry(string $id,int $base,int $max):void { $s=$this->db->prepare('SELECT attempts FROM pending_batches WHERE batch_id=?'); $s->execute([$id]); $n=(int)($s->fetchColumn()?:0)+1; $delay=min($max,$base*(2**min($n-1,10))); $u=$this->db->prepare('UPDATE pending_batches SET attempts=?,next_attempt_at=? WHERE batch_id=?'); $u->execute([$n,time()+$delay,$id]); }
 public function deadLetter(string $id,string $reason,?int $httpStatus=null):void { $this->db->beginTransaction(); try { $s=$this->db->prepare('SELECT payload FROM pending_batches WHERE batch_id=?'); $s->execute([$id]); $payload=$s->fetchColumn(); if($payload!==false){$i=$this->db->prepare('INSERT INTO failed_batches (batch_id,payload,reason,http_status,failed_at) VALUES (?,?,?,?,?) ON CONFLICT(batch_id) DO UPDATE SET payload=excluded.payload,reason=excluded.reason,http_status=excluded.http_status,failed_at=excluded.failed_at'); $i->execute([$id,(string)$payload,substr($reason,0,1000),$httpStatus,time()]);} $u=$this->db->prepare("UPDATE attendance_records SET status='dead_letter',last_error=? WHERE batch_id=? AND status!='acked'"); $u->execute([substr($reason,0,1000),$id]); $this->acknowledge($id); $this->db->commit(); } catch (\Throwable $e) { $this->db->rollBack(); throw $e; } }
 public function counts():array { return ['pending'=>(int)$this->db->query('SELECT COUNT(*) FROM pending_batches')->fetchColumn(),'failed'=>(int)$this->db->query('SELECT COUNT(*) FROM failed_batches')->fetchColumn(),'acked'=>(int)$this->db->query("SELECT COUNT(*) FROM attendance_records WHERE status='acked'")->fetchColumn(),'records_pending'=>(int)$this->db->query("SELECT COUNT(*) FROM attendance_records WHERE status='pending'")->fetchColumn()]; }
 public function knownFingerprints(array $fingerprints):array { if($fingerprints===[])return []; $known=[]; $s=$this->db->prepare('SELECT fingerprint FROM attendance_records WHERE fingerprint=?'); foreach($fingerprints as $f){$s->execute([$f]); if($s->fetchColumn()!==false)$known[$f]=true;} return $known; }
 public function queueAttendanceBatch(string $id,array $payload,array $fingerprints):void { $this->db->beginTransaction(); try { $this->queue($id,$payload); $s=$this->db->prepare("INSERT INTO attendance_records (fingerprint,batch_id,status,first_seen_at) VALUES (?,?, 'pending', ?) ON CONFLICT(fingerprint) DO NOTHING"); foreach($fingerprints as $f)$s->execute([$f,$id,time()]); $this->db->commit(); } catch (\Throwable $e) { $this->db->rollBack(); throw $e; } }
 public function markBatchAcked(string $id):void { $this->db->beginTransaction(); try { $u=$this->db->prepare("UPDATE attendance_records SET status='acked',acked_at=? WHERE batch_id=?"); $u->execute([time(),$id]); $this->acknowledge($id); $this->db->commit(); } catch (\Throwable $e) { $this->db->rollBack(); throw $e; } }
 public function cleanupDiagnostics(array $currentFingerprints):array { $known=$this->knownFingerprints($currentFingerprints); $acked=0;$pending=0;$unresolved=0; foreach($currentFingerprints as $f){ if(!isset($known[$f])){$unresolved++;continue;} $s=$this->db->prepare('SELECT status FROM attendance_records WHERE fingerprint=?'); $s->execute([$f]); $status=(string)$s->fetchColumn(); if($status==='acked')$acked++; elseif($status==='pending')$pending++; else $unresolved++; } return ['device_rows'=>count($currentFingerprints),'acked_rows'=>$acked,'pending_rows'=>$pending,'unresolved_rows'=>$unresolved,'cleanup_eligible_rows'=>0,'cleanup_capability'=>'bulk_clear_all_only','cleanup_enabled'=>false]; }
 public function pruneAckedHistory(int $olderThanSeconds,int $keepCount):int { $cutoff=time()-max(0,$olderThanSeconds); $keep=max(0,$keepCount); $sql="DELETE FROM attendance_records WHERE status='acked' AND acked_at < ? AND fingerprint NOT IN (SELECT fingerprint FROM attendance_records WHERE status='acked' ORDER BY acked_at DESC LIMIT {$keep})"; $s=$this->db->prepare($sql); $s->execute([$cutoff]); return $s->rowCount(); }
 public function get(string $key):?string { $s=$this->db->prepare('SELECT value FROM meta WHERE key=?'); $s->execute([$key]); $v=$s->fetchColumn(); return $v===false?null:(string)$v; }
 public function set(string $key,?string $value):void { $s=$this->db->prepare('INSERT INTO meta (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value'); $s->execute([$key,$value]); }
}
